{% set version = '0.9-10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjava
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rJava_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rJava/rJava_{{ version }}.tar.gz
  sha256: c9934bdd3ae08746c4d4b9faa235af2c147a71235a9af108e58bff11c179fe78

  patches:
    - 0001-Improve-lib-jvm.-so-dylib-dll-loading.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  missing_dso_whitelist:
    - /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/
  script_env:
    - JAVA_HOME

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{ cdt('java-1.7.0-openjdk') }}        # [linux]
    - {{ cdt('java-1.7.0-openjdk-devel') }}  # [linux]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - openjdk                    # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  requires:
    - openjdk                    # [win or linux]
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rJava')"           # [not win]
    - "\"%R%\" -e \"library('rJava')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.rforge.net/rJava/
  license: GPL-2
  summary: Low-level interface to Java VM very much like .C/.Call and friends. Allows creation
    of objects, calling methods and accessing fields.
  license_family: GPL2

extra:
  recipe-maintainers:
    - bgruening
    - johanneskoester
    - mingwandroid
    - sodre

# The original CRAN metadata for this package was:

# Package: rJava
# Version: 0.9-10
# Title: Low-Level R to Java Interface
# Author: Simon Urbanek <simon.urbanek@r-project.org>
# Maintainer: Simon Urbanek <simon.urbanek@r-project.org>
# Depends: R (>= 2.5.0), methods
# Description: Low-level interface to Java VM very much like .C/.Call and friends. Allows creation of objects, calling methods and accessing fields.
# License: GPL-2
# URL: http://www.rforge.net/rJava/
# SystemRequirements: Java JDK 1.2 or higher (for JRI/REngine JDK 1.4 or higher), GNU make
# BugReports: https://github.com/s-u/rJava/issues
# NeedsCompilation: yes
# Packaged: 2018-05-14 20:48:38 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2018-05-29 10:16:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
