{% set version = "0.9-11" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjava
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/rJava_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rJava/rJava_{{ version }}.tar.gz
  sha256: c28ae131456a98f4d3498aa8f6eac9d4df48727008dacff1aa561fc883972c69

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
    - jre/lib/amd64/server/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - openjdk 8.*

  run:
    - r-base
    - openjdk 8.*

test:
  commands:
    - $R -e "library('rJava')"  # [not win]
    - "\"%R%\" -e \"library('rJava')\""  # [win]

about:
  home: http://www.rforge.net/rJava/
  license: GPL-2
  summary: Low-level interface to Java VM very much like .C/.Call and friends. Allows creation
    of objects, calling methods and accessing fields.
  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r
    - sodre
