appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Bt3iXyjbJCzeT+DpgVwUdJ41oMQVTQ3LluzZ5XwsrzijelbNdZmDkEYz6gfzO7LW9cQr9dTcUkFecKgHfq8VEQargtQUEEeZH6l6GKywpD5rL8UYitD+nEl3YiRDfq0DG0ohGACH0iO+uFugZ7mDNyA1NHNhy0o7qbeMjz0rTiQKklaRRkvLRNVcEc8IbvxZh9cloaGSn7mdM+ntBzHU/wrsMVOd6Q28UE8MZZwZnswoYAOnncsn2ZDVhWP9FRC1O9l7VI890wIq4bzhVZH7wGXr63aJeQMQaLw4232k5TMOy98RTQuX96vUPTRse9PETkU4eVBI92DZLPrZwSIOIxXCGUNQDGtjAAISwcR4EP2WTEc7+i2ylK8p747oqoztRkFgGPnjFEUG+Wpyq+oejeVB+jxblUg0TmfGn48+xdCvSsBMZntC7GLWIi52uE1nnoEycEpS3UfAAE47/WWBbnMoe9QZgjuGo1e38TbYRVbS+KpQxJtp0Mv3DHWgaI41D1rxZKIAfibNEU5pDIsApFI7m6sQ6oR/ELLTd8YrNHTIgKwloEhceJdfCTK910hd7WyKlgaYpIM1KFnLhdYxZGrlocZhd0yTIOc5xWWaG527U1j7jo7H3pPprv1Vdq12R5oVx+uV850E4uf71OQxklCw99bXZKtfUWCHuk+ymYc=}
